apiVersion: v1
kind: Service
metadata:
  name: batch-visualizer-auth-service
spec:
  ports:
    - name: "8080"
      port: 8082
      targetPort: 8080
  selector:
    app: batch-visualizer-auth
  type: NodePort
