apiVersion: v1
kind: Service
metadata:
  name: springboot-helloworld
spec:
  ports:
    - name: "8080"
      port: 8082
      targetPort: 8080
  selector:
    app: springboot-helloworld
  type: NodePort
