pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                withMaven(globalMavenSettingsConfig: '', jdk: 'jdk17', maven: 'Maven3.9.6', mavenSettingsConfig: '', traceability: true) {
                    sh 'mvn -f cloud/jenkins/src/demo clean package'
                }
            }
        }
        stage('Docker Build And Push') {
            steps {
                script {
                    docker.withRegistry('https://registry.hub.docker.com', 'seongtaekkim') {
                        image = docker.build("seongtaekkim/demo-springboot:v1");
                        image.push();
                    }
                }
            }
        }
    }
}
